base_config: /home/youhan/ws/VPOCLIP_plus_full/config_final_aug_entropy_single_h2.yaml
runtime:
  device: cuda:0
data:
  train:
    data_dir: /home/youhan/ws/VPOCLIP_plus_full/data/allviews_cs45_lowview50_5_zsl
  val:
    data_dir: /home/youhan/ws/VPOCLIP_plus_full/data/allviews_cs45_lowview50_5_zsl
  text:
    xlsx: /home/youhan/ws/VPOCLIP_plus_full/ntu55_global_descriptions.xlsx
    cache_output: /home/youhan/ws/VPOCLIP_plus_full/work_dir/allviews_lowview50_5_final_aug_entropy_single_h2/text.pt
  dataloader:
    num_workers: 12
    persistent_workers: true
outputs:
  work_dir: /home/youhan/ws/VPOCLIP_plus_full/work_dir/allviews_lowview50_5_final_aug_entropy_single_h2
  auto_run_dir: true
  run_name: allviews_lowview50_5_20260907
train:
  init_checkpoint: null
